insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Ajaloo uurimistöö', '14/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kunsti projekt', '13/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Keemia laboritöö', '2/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Matemaatika kodutöö', '20/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kunsti projekt', '19/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Ajaloo uurimistöö', '24/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Inglise keele essee', '6/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Geograafia esitlus', '20/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Keemia laboritöö', '10/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Keemia laboritöö', '20/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Keemia laboritöö', '4/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Matemaatika kodutöö', '29/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Ajaloo uurimistöö', '17/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Füüsika praktiline töö', '10/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Kunsti projekt', '24/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Muusika esitlus', '2/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Geograafia esitlus', '8/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kunsti projekt', '25/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Ajaloo uurimistöö', '12/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Kehalise kasvatuse test', '25/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Matemaatika kodutöö', '25/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Inglise keele essee', '21/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Füüsika praktiline töö', '13/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Muusika esitlus', '11/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Füüsika praktiline töö', '13/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Keemia laboritöö', '20/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Kehalise kasvatuse test', '6/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Keemia laboritöö', '2/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Keemia laboritöö', '10/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Geograafia esitlus', '9/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Bioloogia eksam', '30/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Geograafia esitlus', '24/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Keemia laboritöö', '21/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Kunsti projekt', '2/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Bioloogia eksam', '15/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Inglise keele essee', '23/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Kehalise kasvatuse test', '7/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Matemaatika kodutöö', '1/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kunsti projekt', '9/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Füüsika praktiline töö', '15/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Matemaatika kodutöö', '8/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Ajaloo uurimistöö', '14/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Kunsti projekt', '20/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Bioloogia eksam', '23/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Ajaloo uurimistöö', '13/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Matemaatika kodutöö', '23/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Muusika esitlus', '19/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Keemia laboritöö', '4/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Inglise keele essee', '26/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Ajaloo uurimistöö', '18/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Bioloogia eksam', '6/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Geograafia esitlus', '3/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Matemaatika kodutöö', '28/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Matemaatika kodutöö', '3/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Füüsika praktiline töö', '8/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Matemaatika kodutöö', '28/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Keemia laboritöö', '26/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Inglise keele essee', '9/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Keemia laboritöö', '12/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Kunsti projekt', '11/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Bioloogia eksam', '2/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Keemia laboritöö', '1/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Kehalise kasvatuse test', '14/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Inglise keele essee', '20/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Kunsti projekt', '28/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Bioloogia eksam', '6/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Matemaatika kodutöö', '21/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Bioloogia eksam', '30/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Keemia laboritöö', '11/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Keemia laboritöö', '23/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Füüsika praktiline töö', '28/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Muusika esitlus', '10/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Ajaloo uurimistöö', '4/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Inglise keele essee', '11/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Geograafia esitlus', '3/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Matemaatika kodutöö', '18/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Kunsti projekt', '20/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Ajaloo uurimistöö', '27/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Matemaatika kodutöö', '11/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Kehalise kasvatuse test', '24/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Keemia laboritöö', '18/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Füüsika praktiline töö', '28/4/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Ajaloo uurimistöö', '4/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Matemaatika kodutöö', '20/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Bioloogia eksam', '13/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Ajaloo uurimistöö', '27/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Kunsti projekt', '29/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Keemia laboritöö', '10/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Kehalise kasvatuse test', '20/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Inglise keele essee', '14/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Ajaloo uurimistöö', '19/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Matemaatika kodutöö', '5/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Füüsika praktiline töö', '20/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Kehalise kasvatuse test', '14/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Ajaloo uurimistöö', '9/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Muusika esitlus', '22/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Kehalise kasvatuse test', '22/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Kehalise kasvatuse test', '5/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Kehalise kasvatuse test', '2/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Inglise keele essee', '7/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Füüsika praktiline töö', '28/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Kunsti projekt', '12/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Keemia laboritöö', '15/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kunsti projekt', '25/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Bioloogia eksam', '10/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Inglise keele essee', '7/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Keemia laboritöö', '5/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Kunsti projekt', '25/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Ajaloo uurimistöö', '1/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Ajaloo uurimistöö', '13/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Bioloogia eksam', '29/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Keemia laboritöö', '28/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Keemia laboritöö', '10/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kehalise kasvatuse test', '28/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Keemia laboritöö', '23/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Kunsti projekt', '3/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Inglise keele essee', '30/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Matemaatika kodutöö', '3/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Ajaloo uurimistöö', '8/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Füüsika praktiline töö', '11/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Keemia laboritöö', '30/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Füüsika praktiline töö', '27/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Muusika esitlus', '26/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Kunsti projekt', '2/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Keemia laboritöö', '19/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Muusika esitlus', '11/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Kunsti projekt', '4/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Kehalise kasvatuse test', '14/2/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Keemia laboritöö', '15/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Kunsti projekt', '18/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Geograafia esitlus', '25/10/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Digital Marketing Masterclass', 'Bioloogia eksam', '21/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Inglise keele essee', '29/8/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Muusika esitlus', '2/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Geograafia esitlus', '7/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Ajaloo uurimistöö', '8/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Web Development Bootcamp', 'Füüsika praktiline töö', '26/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Creative Writing Intensive', 'Bioloogia eksam', '10/11/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Füüsika praktiline töö', '8/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Business Analytics Crash Course', 'Ajaloo uurimistöö', '14/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Geograafia esitlus', '10/12/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Keemia laboritöö', '21/9/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Muusika esitlus', '9/3/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Fitness Training Program', 'Ajaloo uurimistöö', '1/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Bioloogia eksam', '14/7/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Public Speaking Seminar', 'Kehalise kasvatuse test', '23/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Music Production Workshop', 'Ajaloo uurimistöö', '24/6/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Programming 101', 'Kunsti projekt', '23/5/2025');
insert into assignments (kursus, ülesande_nimi, date) values ('Photography Workshop', 'Matemaatika kodutöö', '22/1/2026');
insert into assignments (kursus, ülesande_nimi, date) values ('Graphic Design Fundamentals', 'Geograafia esitlus', '25/1/2026');
