insert into books (raamatu_id, raamatu_nimi, autor, genre) values (1, 'Pride and Prejudice', 'Michael Davis', 'comedy');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (2, 'The Lord of the Rings', 'David Lee', 'horror');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (3, 'The Great Gatsby', 'Kevin Martinez', 'horror');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (4, 'The Secret Garden', 'Emily Johnson', 'romance');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (5, 'The Secret Garden', 'Michael Davis', 'horror');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (6, 'The Lord of the Rings', 'Michael Davis', 'action');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (7, 'The Great Gatsby', 'Jessica Wilson', 'thriller');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (8, 'The Catcher in the Rye', 'Kevin Martinez', 'adventure');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (9, 'Pride and Prejudice', 'Brian Garcia', 'comedy');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (10, 'Harry Potter and the Sorcerer''s Stone', 'John Smith', 'sci-fi');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (11, 'The Great Gatsby', 'John Smith', 'horror');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (12, 'The Secret Garden', 'Jessica Wilson', 'sci-fi');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (13, 'The Lord of the Rings', 'Sarah Brown', 'romance');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (14, 'Pride and Prejudice', 'Kevin Martinez', 'romance');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (15, 'The Great Gatsby', 'Emily Johnson', 'thriller');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (16, 'The Catcher in the Rye', 'Michael Davis', 'adventure');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (17, 'The Great Gatsby', 'Kevin Martinez', 'thriller');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (18, '1984', 'Amanda Thompson', 'comedy');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (19, 'The Catcher in the Rye', 'Olivia Rodriguez', 'horror');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (20, 'Harry Potter and the Sorcerer''s Stone', 'Brian Garcia', 'fantasy');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (21, 'Alice''s Adventures in Wonderland', 'Olivia Rodriguez', 'sci-fi');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (22, 'The Lord of the Rings', 'Jessica Wilson', 'romance');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (23, 'Alice''s Adventures in Wonderland', 'Olivia Rodriguez', 'mystery');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (24, 'Alice''s Adventures in Wonderland', 'Michael Davis', 'comedy');
insert into books (raamatu_id, raamatu_nimi, autor, genre) values (25, 'The Great Gatsby', 'Kevin Martinez', 'horror');
