insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Scorton');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Espinay');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A modern and sleek design with plenty of natural light', 'Burress');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Breslane');
insert into courses (kursus, description, id) values ('Programming 101', 'A luxurious and elegant setting with high-end finishes', 'MacKnockiter');
insert into courses (kursus, description, id) values ('Programming 101', 'A luxurious and elegant setting with high-end finishes', 'Dahlgren');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Klagges');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Benley');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A luxurious and elegant setting with high-end finishes', 'Dicty');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A cozy and inviting space perfect for relaxing', 'Brearton');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A charming and rustic atmosphere with a fireplace', 'Matula');
insert into courses (kursus, description, id) values ('Programming 101', 'A luxurious and elegant setting with high-end finishes', 'Salisbury');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A cozy and inviting space perfect for relaxing', 'Peyton');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'Chesters');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A modern and sleek design with plenty of natural light', 'MacGray');
insert into courses (kursus, description, id) values ('Programming 101', 'A luxurious and elegant setting with high-end finishes', 'Milan');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Lethardy');
insert into courses (kursus, description, id) values ('Programming 101', 'A minimalist and clean aesthetic with pops of color', 'Slym');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A minimalist and clean aesthetic with pops of color', 'Stannah');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'Mainston');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A charming and rustic atmosphere with a fireplace', 'Roughey');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A luxurious and elegant setting with high-end finishes', 'McBain');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A cozy and inviting space perfect for relaxing', 'le Keux');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A modern and sleek design with plenty of natural light', 'Porrett');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Jorcke');
insert into courses (kursus, description, id) values ('Programming 101', 'A modern and sleek design with plenty of natural light', 'Lunam');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Swedeland');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A minimalist and clean aesthetic with pops of color', 'Beels');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Lambert-Ciorwyn');
insert into courses (kursus, description, id) values ('Programming 101', 'A modern and sleek design with plenty of natural light', 'Gudeman');
insert into courses (kursus, description, id) values ('Programming 101', 'A minimalist and clean aesthetic with pops of color', 'Tyt');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A charming and rustic atmosphere with a fireplace', 'Elderbrant');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A minimalist and clean aesthetic with pops of color', 'Umpleby');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Limb');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Naulty');
insert into courses (kursus, description, id) values ('Programming 101', 'A modern and sleek design with plenty of natural light', 'Mellodey');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A charming and rustic atmosphere with a fireplace', 'Lestrange');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A modern and sleek design with plenty of natural light', 'Dust');
insert into courses (kursus, description, id) values ('Programming 101', 'A charming and rustic atmosphere with a fireplace', 'Mingardi');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Lavington');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A cozy and inviting space perfect for relaxing', 'Maddison');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A minimalist and clean aesthetic with pops of color', 'Iacabucci');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'David');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A cozy and inviting space perfect for relaxing', 'Pacheco');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Godar');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Woodyeare');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A cozy and inviting space perfect for relaxing', 'Bamborough');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A luxurious and elegant setting with high-end finishes', 'Impleton');
insert into courses (kursus, description, id) values ('Programming 101', 'A charming and rustic atmosphere with a fireplace', 'Seres');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Atwood');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Sandaver');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A luxurious and elegant setting with high-end finishes', 'Rowat');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Syms');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Antrum');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Carnier');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Seagrave');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A luxurious and elegant setting with high-end finishes', 'Nutbeem');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Turnbull');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Spacey');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A charming and rustic atmosphere with a fireplace', 'Wadley');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A luxurious and elegant setting with high-end finishes', 'Pagelsen');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Jacke');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Gavrieli');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A minimalist and clean aesthetic with pops of color', 'Morrilly');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A charming and rustic atmosphere with a fireplace', 'Kersting');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Tuftin');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Kinkade');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A minimalist and clean aesthetic with pops of color', 'Maden');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Collar');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A charming and rustic atmosphere with a fireplace', 'Kulicke');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Petz');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A luxurious and elegant setting with high-end finishes', 'Whight');
insert into courses (kursus, description, id) values ('Programming 101', 'A charming and rustic atmosphere with a fireplace', 'Delgardo');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Swan');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A modern and sleek design with plenty of natural light', 'Smewin');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A modern and sleek design with plenty of natural light', 'Grunguer');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A charming and rustic atmosphere with a fireplace', 'Choules');
insert into courses (kursus, description, id) values ('Programming 101', 'A minimalist and clean aesthetic with pops of color', 'Kopec');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A charming and rustic atmosphere with a fireplace', 'Cardello');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A modern and sleek design with plenty of natural light', 'Klamp');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Wisdish');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Kryzhov');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Swinbourne');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A luxurious and elegant setting with high-end finishes', 'Lepper');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A charming and rustic atmosphere with a fireplace', 'Calkin');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A charming and rustic atmosphere with a fireplace', 'Rojel');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A modern and sleek design with plenty of natural light', 'Jonk');
insert into courses (kursus, description, id) values ('Programming 101', 'A modern and sleek design with plenty of natural light', 'Ellse');
insert into courses (kursus, description, id) values ('Programming 101', 'A minimalist and clean aesthetic with pops of color', 'Sumner');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A charming and rustic atmosphere with a fireplace', 'Pandya');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Shelp');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'McGlashan');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Hatchett');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'Vagg');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Filippucci');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A modern and sleek design with plenty of natural light', 'Lamps');
insert into courses (kursus, description, id) values ('Programming 101', 'A charming and rustic atmosphere with a fireplace', 'Wonfor');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A charming and rustic atmosphere with a fireplace', 'Salvage');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A minimalist and clean aesthetic with pops of color', 'Mellings');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Huncote');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A luxurious and elegant setting with high-end finishes', 'Faich');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A modern and sleek design with plenty of natural light', 'Sesser');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A charming and rustic atmosphere with a fireplace', 'Timewell');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A charming and rustic atmosphere with a fireplace', 'McTavish');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A charming and rustic atmosphere with a fireplace', 'Groarty');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A minimalist and clean aesthetic with pops of color', 'Biddlecombe');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A modern and sleek design with plenty of natural light', 'Corten');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Jeanneau');
insert into courses (kursus, description, id) values ('Programming 101', 'A luxurious and elegant setting with high-end finishes', 'Beadle');
insert into courses (kursus, description, id) values ('Programming 101', 'A cozy and inviting space perfect for relaxing', 'Dumbrell');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A luxurious and elegant setting with high-end finishes', 'Guillond');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'Doxsey');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Gayden');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A modern and sleek design with plenty of natural light', 'Rochford');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Tomes');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A luxurious and elegant setting with high-end finishes', 'Peskin');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A luxurious and elegant setting with high-end finishes', 'Roskilly');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Burle');
insert into courses (kursus, description, id) values ('Programming 101', 'A modern and sleek design with plenty of natural light', 'Soden');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'Joffe');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A charming and rustic atmosphere with a fireplace', 'Traviss');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A cozy and inviting space perfect for relaxing', 'Darmody');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Vautin');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A modern and sleek design with plenty of natural light', 'Constable');
insert into courses (kursus, description, id) values ('Programming 101', 'A minimalist and clean aesthetic with pops of color', 'Sever');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'Aspell');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A minimalist and clean aesthetic with pops of color', 'McCosker');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A luxurious and elegant setting with high-end finishes', 'Tassell');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A charming and rustic atmosphere with a fireplace', 'Garside');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'McQuillan');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A minimalist and clean aesthetic with pops of color', 'Josefs');
insert into courses (kursus, description, id) values ('Programming 101', 'A luxurious and elegant setting with high-end finishes', 'Veale');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A minimalist and clean aesthetic with pops of color', 'Knotton');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A cozy and inviting space perfect for relaxing', 'McGiven');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A luxurious and elegant setting with high-end finishes', 'Larkkem');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'McVitty');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A luxurious and elegant setting with high-end finishes', 'Coweuppe');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A modern and sleek design with plenty of natural light', 'Novelli');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A luxurious and elegant setting with high-end finishes', 'Leek');
insert into courses (kursus, description, id) values ('Programming 101', 'A minimalist and clean aesthetic with pops of color', 'Herries');
insert into courses (kursus, description, id) values ('Programming 101', 'A modern and sleek design with plenty of natural light', 'Shervil');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'Buddock');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A cozy and inviting space perfect for relaxing', 'Elcox');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A minimalist and clean aesthetic with pops of color', 'Whittam');
insert into courses (kursus, description, id) values ('Photography Workshop', 'A cozy and inviting space perfect for relaxing', 'Whitechurch');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A charming and rustic atmosphere with a fireplace', 'Wadman');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A modern and sleek design with plenty of natural light', 'Zylberdik');
insert into courses (kursus, description, id) values ('Web Development Bootcamp', 'A cozy and inviting space perfect for relaxing', 'Strother');
insert into courses (kursus, description, id) values ('Graphic Design Fundamentals', 'A modern and sleek design with plenty of natural light', 'Amis');
insert into courses (kursus, description, id) values ('Digital Marketing Masterclass', 'A cozy and inviting space perfect for relaxing', 'Bradnock');
