insert into enrollments (user_id, kursus, date) values ('Abdel Mottley', 'Graphic Design Fundamentals', '25/12/2025');
insert into enrollments (user_id, kursus, date) values ('Johannes Oxshott', 'Programming 101', '13/9/2025');
insert into enrollments (user_id, kursus, date) values ('Robinia Bailie', 'Digital Marketing Masterclass', '10/5/2025');
insert into enrollments (user_id, kursus, date) values ('Ring Mitcham', 'Data Science Crash Course', '20/12/2025');
insert into enrollments (user_id, kursus, date) values ('Ginny Lamborne', 'Programming 101', '10/12/2025');
insert into enrollments (user_id, kursus, date) values ('Dougy Pashler', 'Digital Marketing Masterclass', '27/11/2025');
insert into enrollments (user_id, kursus, date) values ('Evanne Chalkly', 'Web Development Bootcamp', '26/1/2026');
insert into enrollments (user_id, kursus, date) values ('Veronika Sapena', 'Digital Marketing Masterclass', '25/9/2025');
insert into enrollments (user_id, kursus, date) values ('Roberta Foulks', 'Digital Marketing Masterclass', '3/2/2026');
insert into enrollments (user_id, kursus, date) values ('Darryl Wyatt', 'Digital Marketing Masterclass', '28/8/2025');
insert into enrollments (user_id, kursus, date) values ('Esme Darwen', 'Graphic Design Fundamentals', '10/10/2025');
insert into enrollments (user_id, kursus, date) values ('Evelina Kingdon', 'Data Science Crash Course', '9/4/2025');
insert into enrollments (user_id, kursus, date) values ('Eba Blunn', 'Digital Marketing Masterclass', '10/4/2025');
insert into enrollments (user_id, kursus, date) values ('Geri Oloman', 'Data Science Crash Course', '20/10/2025');
insert into enrollments (user_id, kursus, date) values ('Cherice Tussaine', 'Data Science Crash Course', '28/7/2025');
insert into enrollments (user_id, kursus, date) values ('Justen Dewett', 'Programming 101', '23/4/2025');
insert into enrollments (user_id, kursus, date) values ('Kelly Semered', 'Programming 101', '9/3/2025');
insert into enrollments (user_id, kursus, date) values ('Paxon Cheke', 'Web Development Bootcamp', '28/11/2025');
insert into enrollments (user_id, kursus, date) values ('Larry Collett', 'Web Development Bootcamp', '16/7/2025');
insert into enrollments (user_id, kursus, date) values ('Tessi Kagan', 'Programming 101', '24/9/2025');
insert into enrollments (user_id, kursus, date) values ('Hugues Derington', 'Web Development Bootcamp', '5/5/2025');
insert into enrollments (user_id, kursus, date) values ('Ken Burkitt', 'Programming 101', '4/4/2025');
insert into enrollments (user_id, kursus, date) values ('Cy Lamputt', 'Programming 101', '23/8/2025');
insert into enrollments (user_id, kursus, date) values ('Terrye Clewarth', 'Programming 101', '3/2/2026');
insert into enrollments (user_id, kursus, date) values ('Saundra Lawlie', 'Data Science Crash Course', '17/6/2025');
insert into enrollments (user_id, kursus, date) values ('Lanny Covely', 'Graphic Design Fundamentals', '13/1/2026');
insert into enrollments (user_id, kursus, date) values ('Charley Fautley', 'Digital Marketing Masterclass', '31/5/2025');
insert into enrollments (user_id, kursus, date) values ('Orelle Sanpher', 'Data Science Crash Course', '3/10/2025');
insert into enrollments (user_id, kursus, date) values ('Lisa Osband', 'Graphic Design Fundamentals', '22/9/2025');
insert into enrollments (user_id, kursus, date) values ('Kacey Rubertelli', 'Data Science Crash Course', '14/11/2025');
insert into enrollments (user_id, kursus, date) values ('Jeralee Rihanek', 'Data Science Crash Course', '5/3/2025');
insert into enrollments (user_id, kursus, date) values ('Delmer Vango', 'Digital Marketing Masterclass', '1/4/2025');
insert into enrollments (user_id, kursus, date) values ('Ruben Proske', 'Digital Marketing Masterclass', '26/11/2025');
insert into enrollments (user_id, kursus, date) values ('Bertha Tookill', 'Data Science Crash Course', '19/12/2025');
insert into enrollments (user_id, kursus, date) values ('Frederik Dalla', 'Graphic Design Fundamentals', '31/7/2025');
insert into enrollments (user_id, kursus, date) values ('Pandora Valeri', 'Data Science Crash Course', '18/12/2025');
insert into enrollments (user_id, kursus, date) values ('Ardith Van Geffen', 'Data Science Crash Course', '20/12/2025');
insert into enrollments (user_id, kursus, date) values ('Junie Christoffels', 'Graphic Design Fundamentals', '24/1/2026');
insert into enrollments (user_id, kursus, date) values ('Fina Betz', 'Graphic Design Fundamentals', '6/2/2026');
insert into enrollments (user_id, kursus, date) values ('Melina Petrolli', 'Digital Marketing Masterclass', '1/7/2025');
insert into enrollments (user_id, kursus, date) values ('Cornela Bleasby', 'Digital Marketing Masterclass', '27/8/2025');
insert into enrollments (user_id, kursus, date) values ('Erina Burris', 'Graphic Design Fundamentals', '12/10/2025');
insert into enrollments (user_id, kursus, date) values ('Dino Scarlon', 'Programming 101', '12/7/2025');
insert into enrollments (user_id, kursus, date) values ('Belita Adamsky', 'Programming 101', '17/4/2025');
insert into enrollments (user_id, kursus, date) values ('Delcine Tytcomb', 'Digital Marketing Masterclass', '1/7/2025');
insert into enrollments (user_id, kursus, date) values ('Latrena Pibsworth', 'Graphic Design Fundamentals', '7/5/2025');
insert into enrollments (user_id, kursus, date) values ('Bibby Kindle', 'Programming 101', '7/2/2026');
insert into enrollments (user_id, kursus, date) values ('Siana Buxy', 'Programming 101', '2/10/2025');
insert into enrollments (user_id, kursus, date) values ('Ed Ellard', 'Graphic Design Fundamentals', '10/9/2025');
insert into enrollments (user_id, kursus, date) values ('Eleanora Grayshan', 'Digital Marketing Masterclass', '28/9/2025');
insert into enrollments (user_id, kursus, date) values ('Kaleena Dowson', 'Data Science Crash Course', '25/12/2025');
insert into enrollments (user_id, kursus, date) values ('Scarlett Weatherhogg', 'Programming 101', '8/5/2025');
insert into enrollments (user_id, kursus, date) values ('Derrek Slatford', 'Digital Marketing Masterclass', '16/3/2025');
insert into enrollments (user_id, kursus, date) values ('Jodi Cumming', 'Digital Marketing Masterclass', '29/12/2025');
insert into enrollments (user_id, kursus, date) values ('Nero BoHlingolsen', 'Digital Marketing Masterclass', '24/5/2025');
insert into enrollments (user_id, kursus, date) values ('Theodosia Lant', 'Graphic Design Fundamentals', '6/4/2025');
insert into enrollments (user_id, kursus, date) values ('Alysa De Moreno', 'Digital Marketing Masterclass', '15/3/2025');
insert into enrollments (user_id, kursus, date) values ('Ulrick Seleway', 'Graphic Design Fundamentals', '10/4/2025');
insert into enrollments (user_id, kursus, date) values ('Calv Haddeston', 'Graphic Design Fundamentals', '9/8/2025');
insert into enrollments (user_id, kursus, date) values ('Maribelle Halbard', 'Graphic Design Fundamentals', '4/3/2025');
insert into enrollments (user_id, kursus, date) values ('Ola Chetwynd', 'Graphic Design Fundamentals', '10/8/2025');
insert into enrollments (user_id, kursus, date) values ('Aurie Pollastrone', 'Graphic Design Fundamentals', '11/5/2025');
insert into enrollments (user_id, kursus, date) values ('Jourdan Attenburrow', 'Programming 101', '23/9/2025');
insert into enrollments (user_id, kursus, date) values ('Drusie Irvin', 'Programming 101', '24/10/2025');
insert into enrollments (user_id, kursus, date) values ('Neysa Bick', 'Programming 101', '15/12/2025');
insert into enrollments (user_id, kursus, date) values ('Deny Domotor', 'Programming 101', '11/4/2025');
insert into enrollments (user_id, kursus, date) values ('Celestia Grishunin', 'Web Development Bootcamp', '4/6/2025');
insert into enrollments (user_id, kursus, date) values ('Denys Cannavan', 'Graphic Design Fundamentals', '17/10/2025');
insert into enrollments (user_id, kursus, date) values ('King Jaycocks', 'Digital Marketing Masterclass', '2/4/2025');
insert into enrollments (user_id, kursus, date) values ('Dionisio Donisthorpe', 'Programming 101', '2/5/2025');
insert into enrollments (user_id, kursus, date) values ('Jandy Metson', 'Graphic Design Fundamentals', '27/6/2025');
insert into enrollments (user_id, kursus, date) values ('Dillon Largent', 'Web Development Bootcamp', '6/5/2025');
insert into enrollments (user_id, kursus, date) values ('Kristi Fawloe', 'Graphic Design Fundamentals', '11/6/2025');
insert into enrollments (user_id, kursus, date) values ('Reginald Redshaw', 'Programming 101', '18/11/2025');
insert into enrollments (user_id, kursus, date) values ('Giffie Ortner', 'Graphic Design Fundamentals', '19/2/2026');
insert into enrollments (user_id, kursus, date) values ('Rolando Scalia', 'Programming 101', '17/2/2026');
insert into enrollments (user_id, kursus, date) values ('Martainn Hillin', 'Data Science Crash Course', '13/2/2026');
insert into enrollments (user_id, kursus, date) values ('Carlyle Adelberg', 'Web Development Bootcamp', '6/4/2025');
insert into enrollments (user_id, kursus, date) values ('Lilla Janic', 'Digital Marketing Masterclass', '24/3/2025');
insert into enrollments (user_id, kursus, date) values ('Jory Mordanti', 'Data Science Crash Course', '16/12/2025');
insert into enrollments (user_id, kursus, date) values ('Raymond Barsham', 'Programming 101', '29/12/2025');
insert into enrollments (user_id, kursus, date) values ('Almeda Felton', 'Data Science Crash Course', '29/4/2025');
insert into enrollments (user_id, kursus, date) values ('Odey Ludewig', 'Graphic Design Fundamentals', '14/6/2025');
insert into enrollments (user_id, kursus, date) values ('Sidnee Fontell', 'Data Science Crash Course', '17/12/2025');
insert into enrollments (user_id, kursus, date) values ('Tallia Hyams', 'Programming 101', '20/12/2025');
insert into enrollments (user_id, kursus, date) values ('Christy Gerner', 'Graphic Design Fundamentals', '16/3/2025');
insert into enrollments (user_id, kursus, date) values ('Harper Elven', 'Data Science Crash Course', '3/2/2026');
insert into enrollments (user_id, kursus, date) values ('Emmalyn Vane', 'Data Science Crash Course', '6/5/2025');
insert into enrollments (user_id, kursus, date) values ('Gisella Juara', 'Data Science Crash Course', '7/12/2025');
insert into enrollments (user_id, kursus, date) values ('Edna Potapczuk', 'Web Development Bootcamp', '12/3/2025');
insert into enrollments (user_id, kursus, date) values ('Ainslee Mitrikhin', 'Web Development Bootcamp', '8/4/2025');
insert into enrollments (user_id, kursus, date) values ('Thayne Weild', 'Programming 101', '21/1/2026');
insert into enrollments (user_id, kursus, date) values ('Lilian Burberry', 'Programming 101', '8/7/2025');
insert into enrollments (user_id, kursus, date) values ('Eunice Botley', 'Data Science Crash Course', '27/4/2025');
insert into enrollments (user_id, kursus, date) values ('Melany Bridgen', 'Programming 101', '5/5/2025');
insert into enrollments (user_id, kursus, date) values ('Findlay MacKomb', 'Programming 101', '5/2/2026');
insert into enrollments (user_id, kursus, date) values ('Keven Sadler', 'Digital Marketing Masterclass', '8/12/2025');
insert into enrollments (user_id, kursus, date) values ('Tann Immins', 'Web Development Bootcamp', '5/10/2025');
insert into enrollments (user_id, kursus, date) values ('Christie Allain', 'Digital Marketing Masterclass', '26/7/2025');
insert into enrollments (user_id, kursus, date) values ('Warde Mattisson', 'Web Development Bootcamp', '2/6/2025');
insert into enrollments (user_id, kursus, date) values ('Cassandra Karim', 'Programming 101', '9/11/2025');
insert into enrollments (user_id, kursus, date) values ('Mile Wittey', 'Data Science Crash Course', '18/10/2025');
insert into enrollments (user_id, kursus, date) values ('Kirby McCambridge', 'Data Science Crash Course', '30/8/2025');
insert into enrollments (user_id, kursus, date) values ('Em McGlaughn', 'Data Science Crash Course', '4/1/2026');
insert into enrollments (user_id, kursus, date) values ('Brand Marrable', 'Data Science Crash Course', '30/11/2025');
insert into enrollments (user_id, kursus, date) values ('Olympia Crocker', 'Web Development Bootcamp', '29/11/2025');
insert into enrollments (user_id, kursus, date) values ('Minda Le Barr', 'Data Science Crash Course', '21/12/2025');
insert into enrollments (user_id, kursus, date) values ('Clemmie Baxstar', 'Programming 101', '4/3/2025');
insert into enrollments (user_id, kursus, date) values ('Jandy Fancet', 'Programming 101', '16/3/2025');
insert into enrollments (user_id, kursus, date) values ('Alli Rosenfelt', 'Programming 101', '7/4/2025');
insert into enrollments (user_id, kursus, date) values ('Stacee Hardinge', 'Data Science Crash Course', '19/1/2026');
insert into enrollments (user_id, kursus, date) values ('Tammara Gergher', 'Data Science Crash Course', '23/5/2025');
insert into enrollments (user_id, kursus, date) values ('Dennis Hufton', 'Data Science Crash Course', '14/12/2025');
insert into enrollments (user_id, kursus, date) values ('Dulci Brigdale', 'Graphic Design Fundamentals', '11/2/2026');
insert into enrollments (user_id, kursus, date) values ('Lindon Weston', 'Digital Marketing Masterclass', '10/4/2025');
insert into enrollments (user_id, kursus, date) values ('Yasmin Sandwick', 'Graphic Design Fundamentals', '1/7/2025');
insert into enrollments (user_id, kursus, date) values ('Rosana Lawtie', 'Data Science Crash Course', '2/11/2025');
insert into enrollments (user_id, kursus, date) values ('Ward Trotman', 'Graphic Design Fundamentals', '12/7/2025');
insert into enrollments (user_id, kursus, date) values ('Hurlee Poultney', 'Programming 101', '16/6/2025');
insert into enrollments (user_id, kursus, date) values ('Zedekiah Sutherns', 'Programming 101', '2/9/2025');
insert into enrollments (user_id, kursus, date) values ('Jereme Bramsen', 'Digital Marketing Masterclass', '30/11/2025');
insert into enrollments (user_id, kursus, date) values ('Aleksandr Tilly', 'Graphic Design Fundamentals', '20/6/2025');
insert into enrollments (user_id, kursus, date) values ('Alikee Burghall', 'Graphic Design Fundamentals', '23/10/2025');
insert into enrollments (user_id, kursus, date) values ('Alvinia Twycross', 'Programming 101', '5/1/2026');
insert into enrollments (user_id, kursus, date) values ('Gianni Lidgertwood', 'Graphic Design Fundamentals', '14/5/2025');
insert into enrollments (user_id, kursus, date) values ('Otes Lowton', 'Programming 101', '28/7/2025');
insert into enrollments (user_id, kursus, date) values ('Gui Grane', 'Data Science Crash Course', '1/7/2025');
insert into enrollments (user_id, kursus, date) values ('Armand Taffee', 'Data Science Crash Course', '10/8/2025');
insert into enrollments (user_id, kursus, date) values ('Sigismund Callam', 'Graphic Design Fundamentals', '2/7/2025');
insert into enrollments (user_id, kursus, date) values ('Evan Cleeves', 'Graphic Design Fundamentals', '30/11/2025');
insert into enrollments (user_id, kursus, date) values ('Fanny Bothams', 'Programming 101', '20/4/2025');
insert into enrollments (user_id, kursus, date) values ('Liuka Whates', 'Programming 101', '17/3/2025');
insert into enrollments (user_id, kursus, date) values ('Genna Christy', 'Graphic Design Fundamentals', '1/6/2025');
insert into enrollments (user_id, kursus, date) values ('Sandra Froggatt', 'Digital Marketing Masterclass', '22/12/2025');
insert into enrollments (user_id, kursus, date) values ('Marnie Fussey', 'Digital Marketing Masterclass', '14/11/2025');
insert into enrollments (user_id, kursus, date) values ('Ardelle Valenta', 'Graphic Design Fundamentals', '22/4/2025');
insert into enrollments (user_id, kursus, date) values ('Isabella Adkin', 'Digital Marketing Masterclass', '11/5/2025');
insert into enrollments (user_id, kursus, date) values ('Elaina By', 'Data Science Crash Course', '9/5/2025');
insert into enrollments (user_id, kursus, date) values ('Mandi Comar', 'Digital Marketing Masterclass', '22/7/2025');
insert into enrollments (user_id, kursus, date) values ('Merell Moralis', 'Programming 101', '2/7/2025');
insert into enrollments (user_id, kursus, date) values ('Berrie Sherston', 'Data Science Crash Course', '18/12/2025');
insert into enrollments (user_id, kursus, date) values ('Kit Hewson', 'Web Development Bootcamp', '2/10/2025');
insert into enrollments (user_id, kursus, date) values ('Berti Yaakov', 'Data Science Crash Course', '19/5/2025');
insert into enrollments (user_id, kursus, date) values ('Kerrie Harral', 'Programming 101', '30/4/2025');
insert into enrollments (user_id, kursus, date) values ('Maisie Kobu', 'Web Development Bootcamp', '6/12/2025');
insert into enrollments (user_id, kursus, date) values ('Kara-lynn Corbin', 'Graphic Design Fundamentals', '4/5/2025');
insert into enrollments (user_id, kursus, date) values ('Kelcey Wessell', 'Web Development Bootcamp', '23/3/2025');
insert into enrollments (user_id, kursus, date) values ('Ines Schrir', 'Web Development Bootcamp', '9/3/2025');
insert into enrollments (user_id, kursus, date) values ('Gan Mulrean', 'Digital Marketing Masterclass', '13/6/2025');
insert into enrollments (user_id, kursus, date) values ('Beatriz Skelbeck', 'Digital Marketing Masterclass', '20/1/2026');
